version: '3.9'

services:
  db:
    container_name: pg
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgres
    networks:
      - nestjs-project

  dbadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - nestjs-project

volumes:
  postgres-data:
  pgadmin-data:


networks:
  nestjs-project:
    driver: bridge
